require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.gitsigns"
require "user.treesitter"
-- require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
-- require "user.toggleterm"
require "user.impatient"
-- require "user.indentline"
require "user.autocommands"
-- require "user.transparency"
require "user.rusttools"
require "user.rust_analyzer"
require "user.catppuccin"
require "user.colorscheme"
require "user.neovide"
